[project]
name = "research-paper-curator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sreyanunna", email = "nunnasreya@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
research-paper-curator = "research_paper_curator:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
